### ISSUE TITLE
Model and code

### ISSUE THREAD

**Issue by Hitman47777** [16lemoing/dot#1]

**Comment by 16lemoing** [comment]
We plan to release everything within the next two weeks.

**Comment by vishnumh** [comment]
Hey,
Awesome work and excited about your repo! Understand the release plan, but any chance of a sneak peek on the visualization sooner? The visualization is super cool compared to previous works. 

Thanks

**Comment by 16lemoing** [comment]
Hi,

Thank you for your patience.
In the end it was easier to release everything at once.

**Comment by XiaoyuShi97** [comment]
Hi, when downloading the checkpoint, I got 404 error. Could you please have a check?

**Comment by jermainn** [comment]
I also got an error when I tried to download the checkpoint. Could you please provide other channel for downloading?

**Comment by 16lemoing** [comment]
Hi, thanks for your feedback. There was a typo in the download links. This should be fixed now.
