### ISSUE TITLE
The performerance of sparse point tracker

### ISSUE THREAD

**Issue by Howtian** [16lemoing/dot#11]
Hi, thanks for this excellent work. 
I would like to know if the cotracker2 used in dot has been improved or retrained? Because when I tried to replace the cotracker in the dot with the official version of cotracker2, there was a significant decrease in performance.

**Comment by 16lemoing** [comment]
Hi @Howtian ! We use the officially released checkpoints as well. We do not observe a significant decrease in performance. On most datasets we observe that the performance is on par with or slightly better than CoTracker.
