### ISSUE TITLE
Training code for optical flow and point tracking

### ISSUE THREAD

**Issue by danqu130** [16lemoing/dot#14]
Thank you for open-sourcing this impressive work. 

The publicly available pre-trained weights contain retrained optical flow and point tracking models, are there any plans to open source the corresponding training code? It would be great to have a good code framework compatible with training for these tasks!

**Comment by 16lemoing** [comment]
Hi @danqu130, thank you for your interest in our work!

The point tracking models are off-the-shelf models (not retrained) so you may refer to the original works (e.g., CoTracker, TAPIR...) for training details.

The optical flow models are indeed retrained and we already include the training code https://github.com/16lemoing/dot#training 

Hope that helps!

**Comment by danqu130** [comment]
Thanks for your reply!
