### ISSUE TITLE
Choose Checkpoint

### ISSUE THREAD

**Issue by emlcpfx** [16lemoing/dot#16]
Hi, how do I choose which checkpoint this is using? As in CoTracker2 vs TAPIR, etc?

**Comment by emlcpfx** [comment]
Nevermind, found it in the base_options.py file.

But while we're here, are there any settings I should be looking for that might give even more accurate results, even at the cost of processing time?

**Comment by 16lemoing** [comment]
Hi, after the choice of the model other important factors for speed performance trade-off are the number of initial tracks `--num_tracks` (the higher the better but also the slower) and the resolution used for inference (same).
